/* import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>

  <header className="border-b">

    <div className="max-w-md mx-auto px-4 py-3 flex justify-between">

      <a href="/" className="font-medium">
        PhotoBox
      </a>

      <a href="/events" className="text-sm text-gray-500">
        Dashboard
      </a>

    </div>

  </header>

  {children}

</body>

    </html>
  );
}
 */




import Link from "next/link";

export default function HomePage() {

  return (

    <main className="min-h-screen bg-white">

      <div className="max-w-md mx-auto px-6 py-12">

        <h1 className="text-3xl font-semibold text-gray-900 mb-2">
          PhotoBox
        </h1>

        <p className="text-gray-500 mb-10">
          Private event photo sharing
        </p>


        <div className="space-y-4">

          <Link
            href="/events"
            className="block w-full bg-black text-white py-4 rounded-lg text-center"
          >
            Host Dashboard
          </Link>


          <Link
            href="/join"
            className="block w-full border border-gray-300 py-4 rounded-lg text-center"
          >
            Join an Event
          </Link>

        </div>


        <p className="text-xs text-gray-400 mt-10 text-center">
          photobox.shadowlab.online
        </p>

      </div>

    </main>

  );

}
