import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>

  <header className="border-b">

    <div className="max-w-md mx-auto px-4 py-3 flex justify-between">

      <a href="/" className="font-medium">
        PhotoBox
      </a>

      <a href="/events" className="text-sm text-gray-500">
        Dashboard
      </a>

    </div>

  </header>

  {children}

</body>

    </html>
  );
}
